version: 2

project_name: dashboard-linter

builds:
  - id: dashboard-linter
    main: .
    binary: dashboard-linter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: dashboard-linter
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'
  groups:
    - title: Dependencies
      regexp: '^.*?(build|chore)\(deps\)!?:.+$'
      order: 100
    - title: Others
      order: 999

release:
  github:
    owner: grafana
    name: dashboard-linter
  draft: false
  prerelease: auto
