on: [push, pull_request]
name: Build
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        persist-credentials: false
    - name: Build
      run: go build ./
